channels:
  - conda-forge
dependencies:
  - python < 3.11
  - pip
  - pip:
    - git+https://github.com/sterinaldi/FIGARO.git
    - numpy < 2
    - git+https://github.com/thomasckng/pop_models_lvk.git
