channels:
  - conda-forge
dependencies:
  - python < 3.11
  - pip
  - pip:
    - git+https://github.com/sterinaldi/pop_models_lvk.git
    - git+https://github.com/sterinaldi/FIGARO.git
    - git+https://github.com/sterinaldi/galleon.git
