import numpy as np
from figaro.cosmology import CosmologicalParameters
from scipy.spatial.distance import jensenshannon
from figaro.load import load_density
from tqdm import tqdm
import dill
import paths
import multiprocessing
import sys

# Mass distribution
from population_models.mass import plpeak # from from https://github.com/sterinaldi/cbc_pdet

# Redshift distribution
def p_z(z, H0):
    Omega = CosmologicalParameters(H0/100., 0.315, 0.685, -1., 0., 0.)
    return Omega.ComovingVolumeElement(z)/((1+z)*Omega.dDLdz(z))

label = 'simulation'
outdir = paths.data / label

print("Preparing model pdfs...")
grid_label = "grid"
try:
    mz, H0, dL, model_pdf = np.load(outdir / f"../{grid_label}.npz").values()
except Exception as e:
    print(f"Error loading {grid_label}.npz: {e}")
    print("Generating model pdfs...")
    mz = np.linspace(1,200,90)
    H0 = np.linspace(5,150,500)
    dL = np.linspace(10, 25000, 80)

    # Calculate source-frame population model pdf for each H0
    model_pdf = []
    for h0 in tqdm(H0, desc = 'H0'):
        z = CosmologicalParameters(h0/100., 0.315, 0.685, -1., 0., 0.).Redshift(dL) # shape = (len(dL))
        m = np.einsum("i, j -> ij", mz, np.reciprocal(1+z)) # shape = (len(mz), len(dL))
        model_pdf_m = plpeak(m) # shape = (len(mz), len(dL))
        model_pdf_z = p_z(z, h0) # shape = (len(z))
        model_pdf.append(np.einsum("ij, j -> ij", model_pdf_m, model_pdf_z)) # shape = (len(mz), len(dL))
    model_pdf = np.array(model_pdf) # shape = (len(H0), len(mz), len(dL))

    # Load selection function
    with open(outdir / '../selection_function.pkl', 'rb') as f: # selection_function.pkl is generated by generate_selection_function.py
        selfunc_interp = dill.load(f)
    def selection_function(x):
        return selfunc_interp(x)
    
    grid = [np.transpose(np.meshgrid(mz, dL)) for i in H0] # shape = (len(H0), len(mz), len(dL), 2)
    SE_grid = np.array([selection_function(grid[i]) for i in tqdm(range(len(H0)), desc = 'selection function grid')]) # shape = (len(H0), len(mz), len(dL))
    model_pdf *= SE_grid # shape = (len(H0), len(mz), len(dL))

    np.savez(outdir / f"../{grid_label}.npz", mz=mz, H0=H0, dL=dL, model_pdf=model_pdf)

print("Reading bounds and draws...")
draws = load_density(outdir / f"draws/draws_observed_{label}.json") # follow README.md to generate draws

bounds = np.loadtxt(outdir / "jsd_bounds.txt") # jsd_bounds.txt is generated by simulate_posterior_samples.py

print("Preparing H0 inference...")
# Mask out mz where there is no sample
_mz_mask = [mz[k] <= bounds[0][1] and mz[k] >= bounds[0][0] for k in range(len(mz))]
mz_short = mz[_mz_mask]

_dL_mask = [dL[k] <= bounds[1][1] and dL[k] >= bounds[1][0] for k in range(len(dL))]
dL_short = dL[_dL_mask]

model_pdf_short = model_pdf[:, _mz_mask, :][:, :, _dL_mask] # shape = (len(H0), len(mz_short), len(dL_short))

grid = np.transpose(np.meshgrid(mz_short, dL_short)) # shape = (len(mz_short), len(dL_short), 2)
figaro_pdf = np.array([draw.pdf(grid) for draw in draws]) # shape = (len(draws), len(mz_short), len(dL_short))

def compute_jsd_for_draw(args):
    figaro_pdf_j, model_pdf_short = args
    return [jensenshannon(model_pdf_short[h].ravel(), figaro_pdf_j.ravel()) for h in range(len(H0))]

print("Inferring H0...")
# Compute JSD between (reconstructed observed distributions for each DPGMM draw) and (model mz distributions for each H0)
with multiprocessing.Pool(int(sys.argv[1])) as pool:
    jsd = pool.map(compute_jsd_for_draw, [(figaro_pdf[j], model_pdf_short) for j in range(len(figaro_pdf))])
jsd = np.array(jsd)
# Find H0 that minimizes JSD for each DPGMM draw
H0_samples = H0[np.argmin(jsd, axis=1)]

print("Saving results...")
np.save(outdir / f"H0_samples_{label}.npy", H0_samples) # shape = (len(draws),)
np.save(outdir / f"jsd_{label}.npy", jsd) # shape = (len(draws), len(H0))

print("Done!")
