import numpy as np
from figaro.cosmology import CosmologicalParameters
from scipy.spatial.distance import jensenshannon
from figaro.load import load_density
from tqdm import tqdm
import dill
import paths
import multiprocessing
import sys

# Mass distribution
from population_models.mass import plpeak # from from https://github.com/sterinaldi/cbc_pdet

# Redshift distribution
def p_z(z, H0):
    Omega = CosmologicalParameters(H0/100., 0.315, 0.685, -1., 0., 0.)
    return Omega.ComovingVolumeElement(z)*(1+z)**(-2)/Omega.dDLdz(z)

label = 'simulation'
outdir = paths.data / label

print("Reading bounds and draws...")
bounds = np.loadtxt(outdir / "jsd_bounds.txt") # jsd_bounds.txt is generated by simulate_posterior_samples.py

# Initialize mz and dL using bounds
mz = np.linspace(bounds[0][0], bounds[0][1], 90)
dL = np.linspace(bounds[1][0], bounds[1][1], 80)
H0 = np.linspace(5,150,500)

print("Generating model PDFs for each H0 value...")
# Calculate source-frame population model pdf for each H0
model_pdf = []
for h0 in tqdm(H0, desc = 'H0'):
    z = CosmologicalParameters(h0/100., 0.315, 0.685, -1., 0., 0.).Redshift(dL) # shape = (len(dL))
    m = np.einsum("i, j -> ij", mz, np.reciprocal(1+z)) # shape = (len(mz), len(dL))
    model_pdf_m = plpeak(m) # shape = (len(mz), len(dL))
    model_pdf_z = p_z(z, h0) # shape = (len(z))
    model_pdf.append(np.einsum("ij, j -> ij", model_pdf_m, model_pdf_z)) # shape = (len(mz), len(dL))
model_pdf = np.array(model_pdf) # shape = (len(H0), len(mz), len(dL))

print("Loading selection function and applying to model PDFs...")
# Load selection function
with open(outdir / '../selection_function.pkl', 'rb') as f: # selection_function.pkl is generated by generate_selection_function.py
    selfunc_interp = dill.load(f)
def selection_function(x):
    return selfunc_interp(x)

grid = [np.transpose(np.meshgrid(mz, dL)) for i in H0] # shape = (len(H0), len(mz), len(dL), 2)
SE_grid = np.array([selection_function(grid[i]) for i in tqdm(range(len(H0)), desc = 'selection function grid')]) # shape = (len(H0), len(mz), len(dL))
model_pdf *= SE_grid # shape = (len(H0), len(mz), len(dL))

print("Loading posterior draws...")
draws = load_density(outdir / f"draws/draws_observed_{label}.json") # follow README.md to generate draws

print("Preparing grid and evaluating PDFs for draws...")
grid = np.transpose(np.meshgrid(mz, dL)) # shape = (len(mz), len(dL), 2)
figaro_pdf = np.array([draw.pdf(grid) for draw in draws]) # shape = (len(draws), len(mz), len(dL))

def compute_jsd_for_draw(args):
    figaro_pdf_j, model_pdf = args
    return [jensenshannon(model_pdf[h].ravel(), figaro_pdf_j.ravel()) for h in range(len(H0))]

print("Inferring H0...")
# Compute JSD between (reconstructed observed distributions for each DPGMM draw) and (model mz distributions for each H0)
with multiprocessing.Pool(int(sys.argv[1])) as pool:
    jsd = pool.map(compute_jsd_for_draw, [(figaro_pdf[j], model_pdf) for j in range(len(figaro_pdf))])
jsd = np.array(jsd)
# Find H0 that minimizes JSD for each DPGMM draw
H0_samples = H0[np.argmin(jsd, axis=1)]

print("Saving H0 samples and JSD results...")
np.save(outdir / f"H0_samples.npy", H0_samples) # shape = (len(draws),)
np.save(outdir / f"jsd.npy", jsd) # shape = (len(draws), len(H0))

print("All done!")
