name: build pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10.16
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.16

      - name: Install TeX Live for matplotlib LaTeX rendering
        id: texlive
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super

      - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@v1
        with:
          showyourwork-spec: git+https://github.com/showyourwork/showyourwork.git
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
